/*
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values 
 * do not exceed four million, find the sum of the even-valued terms.
 */

public class Problem2 {

	public static void main(String [] args){
		
		int sum=0;
		int fibo1=1;
		int fibo2=1;
		while (sum<4000000){
			if (fibo1%2==0) sum+=fibo1;
			System.out.print(fibo1+" ");
			int tmp=fibo2;
			fibo2=fibo1+fibo2;
			fibo1=tmp;
		}
		
		System.out.println("\nsum="+sum);
	}
}
